version: '3.8'  # Puedes cambiar esta versión si es necesario

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db  # Nombre del servicio de la base de datos
      DB_DIALECT: ${DB_DIALECT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - db  # Asegura que el servicio 'db' (MySQL) inicie antes del servidor

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Cambia el puerto de la izquierda (host) a 3307 u otro disponible

volumes:
  db-data:
